server:
  port: 10000

spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL??
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.117.207:3339/freemall_product?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 343669209@Hbw123456
    hikari:
      max-lifetime: 120000
  application:
    name: freemall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tDA7cDe2sqWpkBfskwj
      secret-key: ICVmMMcJjtPgCpjxhaOTUG9sbQBvzv
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        sts:
          access-key: LTAI5tDA7cDe2sqWpkBfskwj
          secret-key: ICVmMMcJjtPgCpjxhaOTUG9sbQBvzv

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  logging:
    level:
      com.wavskying.freemallproduct.dao: debug
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
